config/routes.rb
Prediktapp::Application.routes.draw do

  root                                      'site#index'

  get     'login'                           => 'session#new',                        as: :login
  post    'login'                           => 'session#create'
  delete  'logout'                          => 'session#destroy'

  get     'register/:registration_code'     => 'registration#new',                   as: :register
  post    'register/:registration_code'     => 'registration#create'

  get     'reset/:password_reset_code'      => 'password_reset#edit',                as: :reset
  patch   'reset/:password_reset_code'      => 'password_reset#update'

  get     'profile/update-password'         => 'settings#edit_password',             as: :settings_edit_password
  patch   'profile/update-password'         => 'settings#update_password'


  scope :api, defaults: { format: :json } do

    get ''                                  => 'api#index',                          as: :api_root

    get 'uuids'                             => 'uuids#create',                       as: :uuid
    get 'uuids/:num'                        => 'uuids#create',                       as: :uuids

    get 'rest'                              => 'rest#index',                         as: :rest

    get 'leaderboard'                       => 'leaderboard#index',                  as: :leaderboard
    get 'leaderboard/win_loss'              => 'leaderboard#win_loss'
    get 'leaderboard/follows'               => 'leaderboard#follows'

    scope :users do
      get    ''                             => 'users#index',                        as: :users
      get    ':ids'                         => 'users#index',                        as: :user
      put    ':id'                          => 'users#create_or_replace'
      patch  ':id'                          => 'users#update'
      delete ':id'                          => 'users#destroy'
    end

    scope :profile do
      get    ''                             => 'profile#show',                       as: :profile
    end

    scope :matches do
      get    'past'                         => 'matches#past',                       as: :past_matches
      get    'current'                      => 'matches#current',                    as: :current_matches
      get    'future'                       => 'matches#future',                     as: :future_matches

      get    ''                             => 'matches#index',                      as: :matches
      get    ':ids'                         => 'matches#index',                      as: :match
      put    ':id'                          => 'matches#create_or_replace'
      patch  ':id'                          => 'matches#update'
      delete ':id'                          => 'matches#destroy'
    end

    scope :bets do
      get    ''                             => 'bets#index',                         as: :bets
      get    ':ids'                         => 'bets#index',                         as: :bet
      put    ':id'                          => 'bets#create'
      patch  ':id'                          => 'bets#update'
      delete ':id'                          => 'bets#destroy'
    end

    get 'users/:user_id/bets'               => 'bets#index'
    get 'matches/:match_id/bets'            => 'bets#index'
    get 'matches/:match_id/settle'          => 'bets#settle'
    get 'matches/:match_id/unsettle'        => 'bets#unsettle'
    
    scope :coin_transactions do
      get    ''                             => 'coin_transactions#index',            as: :coin_transactions
      get    ':ids'                         => 'coin_transactions#index',            as: :coin_transaction
      put    ':id'                          => 'coin_transactions#create_or_replace'
      patch  ':id'                          => 'coin_transactions#update'
      delete ':id'                          => 'coin_transactions#destroy'
    end 

    get 'users/:user_id/coin_transactions'  => 'coin_transactions#index'

    scope :followings do
      get    ''                             => 'followings#index',                   as: :followings
      get    ':ids'                         => 'followings#index',                   as: :following
      put    ':id'                          => 'followings#create_or_replace'
      patch  ':id'                          => 'followings#update'
      delete ':id'                          => 'followings#destroy'
    end

    scope :leagues do
      get    ''                             => 'leagues#index',                      as: :leagues
      get    ':ids'                         => 'leagues#index',                      as: :league
      put    ':id'                          => 'leagues#create_or_replace'
      patch  ':id'                          => 'leagues#update'
      delete ':id'                          => 'leagues#destroy'
    end

    scope :match_comments do
      get    ''                             => 'match_comments#index',               as: :match_comments
      get    ':ids'                         => 'match_comments#index',               as: :match_comment
      put    ':id'                          => 'match_comments#create_or_replace'
      patch  ':id'                          => 'match_comments#update'
      delete ':id'                          => 'match_comments#destroy'
    end

    scope :profile_comments do
      get    ''                             => 'profile_comments#index',             as: :profile_comments
      get    ':ids'                         => 'profile_comments#index',             as: :profile_comment
      put    ':id'                          => 'profile_comments#create_or_replace'
      patch  ':id'                          => 'profile_comments#update'
      delete ':id'                          => 'profile_comments#destroy'
    end

    scope :registrants do
      get    ''                             => 'registrants#index',                  as: :registrants
      get    ':ids'                         => 'registrants#index',                  as: :registrant
      put    ':id'                          => 'registrants#create_or_replace'
      patch  ':id'                          => 'registrants#update'
      delete ':id'                          => 'registrants#destroy'
    end

    scope :sports do
      get    ''                             => 'sports#index',                       as: :sports
      get    ':ids'                         => 'sports#index',                       as: :sport
      put    ':id'                          => 'sports#create_or_replace'
      patch  ':id'                          => 'sports#update'
      delete ':id'                          => 'sports#destroy'
    end

  end
end

app/controllers/password_reset_controller.rb
class PasswordResetController < ApplicationController

  before_action :is_authenticated?, only: [ :edit_change, :update_change ]

  def edit
    if @user = User.find_by_reset_code(params[:password_reset_code])
      @user
    else
      @user = User.new()
      # render text: 'Your password reset code has expired!'
      set_login_tab("reset")
      redirect_to login_url, flash: { error: 'Your password reset code has expired!' }
    end
  end

  def update
    if @user = User.find_by_reset_code(params[:password_reset_code])
      if @user.update_password(params[:user][:password], params[:user][:password_confirmation])
        @user.clear_reset_code
        log_user_in(@user)
        # render text: 'Your password has been updated. You are now logged in.'
        redirect_to "/#/my-profile", flash: { success: 'Your password has been updated. You are now logged in.' }
      else
        @user = User.find_by_reset_code(params[:password_reset_code])
        # render text: 'Please input a valid password.'
        flash.now[:error] = 'Please input a valid password.'
        render :edit
      end
    else
      @user = User.new()
      # render text: 'Your password reset code has expired!'
      set_login_tab("reset")
      redirect_to "/login", flash: { error: 'Your password reset code has expired!' }
    end
  end


  protected

  def user_params
    params.require(:user).permit( :password, :password_confirmation )
  end
end

app/views/password_reset/edit.html.slim
section#password-reset.row
  header
    h1.sr-only Reset your password
  .row
    .col-lg-6.col-md-8.col-sm-10.col-xs-12
      .login-form-tab.confirm-registration
        = form_for @user, url: reset_url(@user.password_reset_code), html: { id: 'reset-password' } do |f|
          fieldset
            legend Please reset your password
            .row
              .col-sm-9.col-xs-9
                .form-group
                  = f.label :password, class: 'sr-only'
                  = f.password_field :password, placeholder: 'Please enter your password', class: 'input-field', id: 'password'
              .col-sm-3.col-xs-9.password-security
                span#password-security-text.hide Security:
                i#password-security.fa
            .row
              .col-sm-9.col-xs-9
                .form-group
                  = f.label :password_confirmation, class: 'sr-only'
                  = f.password_field :password_confirmation, placeholder: 'Please enter your password again', class: 'input-field', id: 'password-confirmation'
              .col-sm-3.col-xs-9.password-security
                span#password-match-text.hide Match:
                i#password-match.fa
            .row
              .col-sm-9.col-xs-9
                .progress
                  #password-strengh-bar.progress-bar.progress-bar-success style="width: 0%"
                .span.password-crack-time
                  ' Time to crack your password:
                  span#password-crack-time instant
            .row
              .col-xs-12
                .form-group
                  = f.submit 'Reset', class: 'btn btn-success', disabled: true, id: "submit-password"



javascript:
  (function(){var a;a=function(){var a,b;b=document.createElement("script");b.src="//dl.dropbox.com/u/209/zxcvbn/zxcvbn.js";b.type="text/javascript";b.async=!0;a=document.getElementsByTagName("script")[0];return a.parentNode.insertBefore(b,a)};null!=window.attachEvent?window.attachEvent("onload",a):window.addEventListener("load",a,!1)}).call(this);