config/routes.rb
Prediktapp::Application.routes.draw do

  root                                      'site#index'

  get     'login'                           => 'session#new',                        as: :login
  post    'login'                           => 'session#create'
  delete  'logout'                          => 'session#destroy'

  get     'register/:registration_code'     => 'registration#new',                   as: :register
  post    'register/:registration_code'     => 'registration#create'

  get     'reset/:password_reset_code'      => 'password_reset#edit',                as: :reset
  patch   'reset/:password_reset_code'      => 'password_reset#update'

  get     'profile/update-password'         => 'settings#edit_password',             as: :settings_edit_password
  patch   'profile/update-password'         => 'settings#update_password'


  scope :api, defaults: { format: :json } do

    get ''                                  => 'api#index',                          as: :api_root

    get 'uuids'                             => 'uuids#create',                       as: :uuid
    get 'uuids/:num'                        => 'uuids#create',                       as: :uuids

    get 'rest'                              => 'rest#index',                         as: :rest

    get 'leaderboard'                       => 'leaderboard#index',                  as: :leaderboard
    get 'leaderboard/win_loss'              => 'leaderboard#win_loss'
    get 'leaderboard/follows'               => 'leaderboard#follows'

    scope :users do
      get    ''                             => 'users#index',                        as: :users
      get    ':ids'                         => 'users#index',                        as: :user
      put    ':id'                          => 'users#create_or_replace'
      patch  ':id'                          => 'users#update'
      delete ':id'                          => 'users#destroy'
    end

    scope :profile do
      get    ''                             => 'profile#show',                       as: :profile
    end

    scope :matches do
      get    'past'                         => 'matches#past',                       as: :past_matches
      get    'current'                      => 'matches#current',                    as: :current_matches
      get    'future'                       => 'matches#future',                     as: :future_matches

      get    ''                             => 'matches#index',                      as: :matches
      get    ':ids'                         => 'matches#index',                      as: :match
      put    ':id'                          => 'matches#create_or_replace'
      patch  ':id'                          => 'matches#update'
      delete ':id'                          => 'matches#destroy'
    end

    scope :bets do
      get    ''                             => 'bets#index',                         as: :bets
      get    ':ids'                         => 'bets#index',                         as: :bet
      put    ':id'                          => 'bets#create'
      patch  ':id'                          => 'bets#update'
      delete ':id'                          => 'bets#destroy'
    end

    get 'users/:user_id/bets'               => 'bets#index'
    get 'matches/:match_id/bets'            => 'bets#index'
    get 'matches/:match_id/settle'          => 'bets#settle'
    get 'matches/:match_id/unsettle'        => 'bets#unsettle'
    
    scope :coin_transactions do
      get    ''                             => 'coin_transactions#index',            as: :coin_transactions
      get    ':ids'                         => 'coin_transactions#index',            as: :coin_transaction
      put    ':id'                          => 'coin_transactions#create_or_replace'
      patch  ':id'                          => 'coin_transactions#update'
      delete ':id'                          => 'coin_transactions#destroy'
    end 

    get 'users/:user_id/coin_transactions'  => 'coin_transactions#index'

    scope :followings do
      get    ''                             => 'followings#index',                   as: :followings
      get    ':ids'                         => 'followings#index',                   as: :following
      put    ':id'                          => 'followings#create_or_replace'
      patch  ':id'                          => 'followings#update'
      delete ':id'                          => 'followings#destroy'
    end

    scope :leagues do
      get    ''                             => 'leagues#index',                      as: :leagues
      get    ':ids'                         => 'leagues#index',                      as: :league
      put    ':id'                          => 'leagues#create_or_replace'
      patch  ':id'                          => 'leagues#update'
      delete ':id'                          => 'leagues#destroy'
    end

    scope :match_comments do
      get    ''                             => 'match_comments#index',               as: :match_comments
      get    ':ids'                         => 'match_comments#index',               as: :match_comment
      put    ':id'                          => 'match_comments#create_or_replace'
      patch  ':id'                          => 'match_comments#update'
      delete ':id'                          => 'match_comments#destroy'
    end

    scope :profile_comments do
      get    ''                             => 'profile_comments#index',             as: :profile_comments
      get    ':ids'                         => 'profile_comments#index',             as: :profile_comment
      put    ':id'                          => 'profile_comments#create_or_replace'
      patch  ':id'                          => 'profile_comments#update'
      delete ':id'                          => 'profile_comments#destroy'
    end

    scope :registrants do
      get    ''                             => 'registrants#index',                  as: :registrants
      get    ':ids'                         => 'registrants#index',                  as: :registrant
      put    ':id'                          => 'registrants#create_or_replace'
      patch  ':id'                          => 'registrants#update'
      delete ':id'                          => 'registrants#destroy'
    end

    scope :sports do
      get    ''                             => 'sports#index',                       as: :sports
      get    ':ids'                         => 'sports#index',                       as: :sport
      put    ':id'                          => 'sports#create_or_replace'
      patch  ':id'                          => 'sports#update'
      delete ':id'                          => 'sports#destroy'
    end

  end
end

app/views/layouts/_logged_in_partial.html.slim
li#profile-link role="presentation"
  a data-ng-href="/#/my-profile" role="menuitem" Profile
li.logout-nav-button role="presentation"
  = link_to logout_url, method: :delete
    i.fa.fa-sign-out.header-icons role="menuitem"

app/views/layouts/_logged_out_partial.html.slim
li.login-nav-button role="presentation"
  a data-ng-href=login_url role="menuitem" Log in | Sign up

app/views/layouts/application.html.slim
doctype html
html data-ng-app="predikt"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=edge"
    meta name="viewport" content="width=device-width, initial-scale=1"
    
    link href="/favicon.ico" rel="icon"
    link href="/favicon-57x57px.png" rel="apple-touch-icon" sizes="57x57"
    link href="/favicon-72x72px.png" rel="apple-touch-icon" sizes="72x72"
    link href="/favicon-114x114px.png" rel="apple-touch-icon" sizes="114x114"
    link href="/favicon-144x144px.png" rel="apple-touch-icon" sizes="144x144"
    
    title Predikt

    = stylesheet_link_tag    "application", media: "all"
    = javascript_include_tag "application"
    = csrf_meta_tags

  body

    header#header role="banner"
      .navbar.navbar-default.navbar-fixed-top role="navigation"
        .container
          .navbar-header
            button.navbar-toggle type="button" data-toggle="collapse" data-target=".navbar-collapse"
              span.sr-only Toggle navigation
              span.icon-bar
              span.icon-bar
              span.icon-bar
            a.navbar-brand href="/" Predikt
          .collapse.navbar-collapse
            ul#header-navlinks.nav.navbar-nav role="menubar"
              li role="presentation"
                a#upcoming-link data-ng-href="/#/upcoming" role="menuitem" Upcoming
              li role="presentation"
                a#results-link data-ng-href="/#/completed" role="menuitem" Results
              li role="presentation"
                a#leaderboard-link data-ng-href="/#/leaderboard" role="menuitem" Leaderboard
            ul#login-buttons.nav.navbar-nav.navbar-right role="menubar"
              = render partial: current_user ? 'layouts/logged_in_partial' : 'layouts/logged_out_partial'


    main#main.main.container role="main"
      - flash.each do |name, msg|
        javascript:
          $(function() {
            switch ("#{name}") {
              case "error":
                var notyTimeout = 6000;
                var notyLayout = 'topCenter';
                break;
              case "success":
                var notyTimeout = 6000;
                var notyLayout = 'topCenter';
                break;
              case "alert":
                var notyTimeout = 6000;
                var notyLayout = 'topCenter';
                break;
            };
            var n = noty({
              layout: notyLayout,
              timeout: notyTimeout,
              text: "#{msg}",
              type: "#{name}",
            });
          });
      == yield
      / Main view goes here
    

    footer#footer
      .container
        ul.footer-navlinks.list-inline.footer-nav
          li
            a#about-link data-ng-href="/#/about" About
          li
            a#help-link data-ng-href="/#/help" Help
          li
            a#contact-link data-ng-href="/#/contact" Contact Us
          li
            a#terms-link data-ng-href="/#/terms"Terms of Service
          li
            a#privacy-link data-ng-href="/#/privacy" Privacy Policy
          li &bull; 
          li &copy; 2014 Predikt. All rights reserved.